<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SauceDemo_Lockedout</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>b3b56842-aad5-4c84-86be-564ee566c376</testSuiteGuid>
   <testCaseLink>
      <guid>2fbed47a-1113-40dc-a264-b9ef9b1ababa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d7884ff0-c933-412e-89cc-93d5660f6373</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/SauceDemo_Account</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d7884ff0-c933-412e-89cc-93d5660f6373</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>370e5150-5b5a-4a7e-ad05-7b037677e6c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d7884ff0-c933-412e-89cc-93d5660f6373</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>90c9cb8c-250e-4b17-a94c-cafc9af04ffd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
